## We need a base image
FROM mcr.microsoft.com/mssql/server:2017-latest

## let's modify it
RUN mkdir /bu

## and move our database to it
##COPY --from=stage "c:\\docker\\sql\\adventureworks2017.bak"  "/bu"
##COPY --from=stage adventureworks2017.bak /bu
##COPY adventureworks2017.bak /bu
##COPY C:\Docker\SQL\AdventureWorks2017.bak /bu
##COPY C:\\Docker\\SQL\\AdventureWorks2017.bak /bu
##COPY --from=stage C:\Docker\SQL\AdventureWorks2017.bak /bu
##COPY --from=stage C:/Docker/SQL/AdventureWorks2017.bak /bu
##COPY ["C:\Docker\SQL\AdventureWorks2017.bak", "/bu"]
##COPY ["C:\Docker\SQL\AdventureWorks2017.bak"] /bu
##COPY "C:\Docker\SQL\AdventureWorks2017.bak" /bu

##ADD adventureworks2017.bak /bu
ADD C:/Docker/SQL/AdventureWorks2017.bak /bu
