## We need a base image
##FROM mcr.microsoft.com/mssql/server:2017-latest
FROM mcr.microsoft.com/mssql/server:2019-CTP3.0-ubuntu

## let's modify it
RUN mkdir /bu

## copy in the backup
COPY adventureworks2017.bak /bu

